[package]
name = "reploy"
version = "0.1.8"
edition = "2024"
keywords = ["deploy", "ssh"]
authors = ["Carey Wong <cw.cinus@gmail.com>"]

[dependencies]
clap = "4.5.0"
dirs = "6.0.0"
ssh2 = "0.9.5"
regex = "1.11.1"
dialoguer = "0.11.0"
